version: '3.5'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ../nginx/data/nginx:/etc/nginx/conf.d
      - ../nginx/data/certbot/conf:/etc/letsencrypt
      - ../nginx/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    links:
      - frontend:frontend
      # Refer to the 'web' defined in another compose file as 'backend'
      - web:backend

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ../nginx/data/certbot/conf:/etc/letsencrypt
      - ../nginx/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  frontend:
    build:
      context: ../frontend
      args:
        - "api_host=${API_HOST}"
        - "google_api_key=${GOOGLE_API_KEY}"

  web:
    build:
      context: ../server
